### DISCUSSION TITLE
urn:ietf:params:acme:error:tls  remote error: tls: unrecognized name

### DISCUSSION THREAD

**Discussion by yolkhovyy** [go-acme/lego#2090] [Q&A]
Hello, is this the right place to ask for help with the error below? 

```
ime="2024-01-23T04:13:40Z" level=error 
msg="Error renewing certificate from LE: {[mydomain.com](http://mydomain.com/) }"
providerName=certresolver.acme ACME CA="https://acme-v02.api.letsencrypt.org/directory"
error="error: one or more domains had a problem:\n[[mydomain.com](http://mydomain.com/)]
acme: error: 400 :: urn:ietf:params:acme:error:tls :: xx.xx.xx.xx: remote error: tls: unrecognized name\n"
```

It's the latest traefik/letsencrypt (uses github.com/go-acme/lego/v4 v4.14.0), running in a container in a docker swarm on a raspberry pi 4. Time to renew certificates and it fails, worked fine so far.

nslookup inside the container resolves all involved hostnames successfully, the same on an external network. Inbound and outbound 80/443 are forwarded/open.

What I've collected so far is here:

**urn:ietf:params:acme:error:tls:**
This error indicates a problem with the TLS (Transport Layer Security) connection during the ACME protocol exchange. It typically means there was an issue with the TLS handshake or communication between the client (your server) and the ACME server.

**remote error: tls: unrecognized name:**
This error suggests that the ACME server received a TLS certificate request for a domain name that it does not recognize or is not associated with the account making the request.  

Any further help is very much appreciated.

**Comment by ldez** [comment]
Hello,

My guess is something related to the characters used by your domain (non-ASCII characters, non-puny coded domain, etc.) or related to your network.

Based on your logs, I think you are a Traefik user, your configuration can help to understand the problem.

**Reply by yolkhovyy** [reply]
Thanks for your response. Domain name consists of ASCII characters, all worked fine until a few days ago, the last time I touched traefik config was about a year ago. My internet provider was recently acquired by a bigger one, got a new modem a few weeks ago - it's zyxel EX5601-T1.

<details>

Traefik network:
```bash
docker network create -d overlay --attachable proxy
```

Traefik docker compose:
```yml
version: "3.3"

networks:
  proxy:
    external: true
  
volumes:
  traefik:
    external: true
  letsencrypt: 
    external: true
  log:
    external: true

configs:
  traefik_users:
    file: /mnt/.../traefik/users

services:
  traefik:
    image: traefik:latest    #v2.9.6
    configs:
      - source: traefik_users
        target: /users
        mode: 444
    ports:
      - "80:80"
      - "443:443"
    command:
      - --api.insecure=false
      - --api.dashboard=true
      # - --api.debug=true

      - --accesslog=true
      - --accesslog.filepath=/var/log/traefik/access.log
      - --accesslog.bufferingsize=100
      - --log.level=ERROR
      - --log.filepath=/var/log/traefik/traefik.log

      - --providers.providersThrottleDuration=10s
      - --providers.file.filename=/config/dynamic.toml
      - --providers.file.watch=true

      - --providers.docker=true
      - --providers.docker.endpoint=unix:///var/run/docker.sock
      - --providers.docker.swarmMode=true
      - --providers.docker.exposedByDefault=false
      - --providers.docker.network=proxy

      - --entrypoints.ep-http.address=:80
      - --entrypoints.ep-https.address=:443

      #- --certificatesresolvers.certresolver.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory
      #- --certificatesresolvers.certresolver.acme.caServer=https://acme-v02.api.letsencrypt.org/directory
      - --certificatesresolvers.certresolver.acme.tlschallenge=true
      #- --certificatesresolvers.certresolver.acme.httpchallenge.entrypoint=ep-http
      - --certificatesresolvers.certresolver.acme.email=...@gmail.com
      - --certificatesresolvers.certresolver.acme.storage=/letsencrypt/acme.json
    volumes:
      - traefik:/config
      - letsencrypt:/letsencrypt
      - log:/var/log
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 3s
      placement:
        constraints: 
          - node.role == manager
          - node.hostname == hostname here
      labels:
        - traefik.enable=true

        # Generic redirect to https
        - traefik.http.middlewares.mw-redirect-to-https.redirectscheme.scheme=https
        - traefik.http.middlewares.mw-redirect-to-https.redirectscheme.permanent=true
        - traefik.http.routers.r-redirect-to-https.rule=hostregexp(`{host:.+}`)
        - traefik.http.routers.r-redirect-to-https.entrypoints=ep-http
        - traefik.http.routers.r-redirect-to-https.middlewares=mw-redirect-to-https

        # Secure Traefik
        - traefik.http.middlewares.mw-traefik-auth.basicauth.usersfile=/users
        - traefik.http.middlewares.mw-traefik-auth.basicauth.realm=traefik
        - traefik.http.routers.r-traefik.entrypoints=ep-https
        - traefik.http.routers.r-traefik.rule=Host(`mydomain.com`) && (PathPrefix(`/api/`) || PathPrefix(`/dashboard/`))
        - traefik.http.routers.r-traefik.tls=true
        - traefik.http.routers.r-traefik.tls.certresolver=certresolver
        - traefik.http.routers.r-traefik.middlewares=mw-traefik-auth
        - traefik.http.routers.r-traefik.service=api@internal
        - traefik.http.services.dummy-service.loadbalancer.server.port=1357
```

Traefik dynamic.toml:
```toml
[http.routers]
  [http.routers.r-foo]
    entrypoints = ["ep-https"]
    service = "s-foo"
    rule = "Host(`foo.mydomain.com`)"
    [http.routers.r-foo.tls]
      certresolver = "certresolver"
  [http.routers.r-bar]
    entrypoints = ["ep-https"]
    service = "s-bar"
    rule = "Host(`bar.mydomain.com`)"
    [http.routers.r-bar.tls]
      certresolver = "certresolver"
  [http.routers.r-baz]
    entrypoints = ["ep-https"]
    service = "s-baz"
    rule = "Host(`baz.mydomain.com`)"
    [http.routers.r-baz.tls]
      certresolver = "certresolver"

[http.services]
  [http.services.s-foo]
    [http.services.s-foo.loadbalancer]
      [[http.services.s-foo.loadbalancer.servers]]
        url = "http://192.168.1.12:12345/"
  [http.services.s-bar]
    [http.services.s-bar.loadbalancer]
      [[http.services.s-bar.loadbalancer.servers]]
        url = "http://192.168.1.12:23456/"
  [http.services.s-baz]
    [http.services.s-baz.loadbalancer]
      [[http.services.s-baz.loadbalancer.servers]]
        url = "http://192.168.1.12:34567/" 
```

</details>
