### DISCUSSION TITLE
Cant generate Cert

### DISCUSSION THREAD

**Discussion by nekromantik** [go-acme/lego#2091] [Q&A]
Hi

So I got a domain I bought from Porkbun and set up Traefik to use Porkbun and ZeroSSL for certs.
However I saw a lot of issues with Porkbun and Lego so I updated my Porkbun to use Cloudflare Nameservers and they propegated fine and now I got entries in Cloudflare. 
Lego adds the TXT records and I can see them in Cloudflare but fails verify.
I get the below error:

```
time="2024-01-27T18:47:06Z" level=error msg="Unable to obtain ACME certificate for domains \"nextcloud.xxx.xyz\": unable to generate a certificate for the domains [nextcloud.xxxx.xyz]: error: one or more domains had a problem:\n[nextcloud.xxxx.xyz] propagation: time limit exceeded: last error: NS dale.ns.cloudflare.com. returned REFUSED for xxx.xyz.\n" providerName=letsencrypt.acme routerName=nextcloud@docker rule="Host(`nextcloud.xxxx.xyz`)" ACME CA="https://acme-staging-v02.api.letsencrypt.org/directory"
```

My config is as below:
```yml
certificatesResolvers:
  letsencrypt:
    acme:
      email: xxxxx
      storage: /etc/traefik/acme.json
      # Use staging caServer for now to not get limited (comment out when in production)
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 5
        resolvers:
          - "1.1.1.153"
          - "1.0.0.1:53"
```
