### DISCUSSION TITLE
_FILE suffix not working for AzureDNS?

### DISCUSSION THREAD

**Discussion by arp-mbender** [go-acme/lego#2254] [Q&A] [answered]
I'm looking at the https://github.com/go-acme/lego/blob/master/providers/dns/azuredns/azuredns.go code and I can't see it taking `_FILE` suffixed values into account. These should supposedly work (see documentation: https://go-acme.github.io/lego/dns/azuredns/). The only thing in the code is a reference to `OIDC_TOKEN_FILE_PATH`, but that doesn't really satisfy the documentation:
> The environment variable names can be suffixed by _FILE to reference a file instead of a value. More information [here](https://go-acme.github.io/lego/dns/#configuration-and-credentials).

Does each provider implement the `_FILE` suffix handling itself? If so, then I can't find any relevant code in the link above. Or is it handled globally by another `.go` file?

I've noticed these values don't appear to work when I was trying to configure the ACME DNS challenge using the `AzureDns` in Traefik. Unfortunately I'm not sure which version is used by Traefik, which is why I'm making a discussion...

By comparison https://github.com/go-acme/lego/blob/master/providers/dns/oraclecloud/oraclecloud.go **has** a section for handling a `_FILE` suffix, but it appears to be used for only one value (where the documentation suggests this is possible for all configuration elements).

EDIT: OK, Found it. It should be globally handled... https://github.com/go-acme/lego/blob/master/platform/config/env/env.go#L144

---

Extracted from Traefik issue.

<details><summary>docker-compose.yml</summary>

```yml
services:
  traefik:
    image: "traefik:v3.1"
    container_name: "traefik"
    env_file:
      - ./azuredns/.env
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt/:/letsencrypt/"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./services/:/services/"
      - "./azuredns/:/azuredns/"
      - "./certs/:/certs/"
      - "/var/log/traefik/:/var/log/traefik/"
```

</details>

<details><summary>traefik.yml</summary>

```yml
entryPoints:
  web:
    address: :80

  websecure:
    asDefault: true
    address: :443
    http:
      tls:
        certResolver: le
        domains:
          - main: "*.domain.com"
            sans: 
              - "domain.com"
certificatesResolvers:
  le:
    acme:
      email: admin@domain.com
      storage: /letsencrypt/acme.json
      caserver: "https://acme-v02.api.letsencrypt.org/directory"
      dnsChallenge:
        provider: azuredns
```

</details>

Finally, I have the following in the `/azuredns/` folder:

- `/azuredns/.env`

```
AZURE_SUBSCRIPTION_ID=<redacted>
AZURE_TENANT_ID=<redacted>
AZURE_CLIENT_ID=<redacted>
AZURE_CLIENT_SECRET_FILE=/azuredns/azuresecret
AZURE_RESOURCE_GROUP=<redacted>
```

- `/azuredns/azuresecret`:

```
MyAzureClientSecret
```

Logs:

```
ERR Unable to obtain ACME certificate for domains error="cannot get ACME client azuredns: discover DNS zones: DefaultAzureCredential: failed to acquire a token.
Attempted credentials:
    EnvironmentCredential: incomplete environment variable configuration. Only AZURE_TENANT_ID and AZURE_CLIENT_ID are set
    WorkloadIdentityCredential: no token file specified. Check pod configuration or set TokenFilePath in the options
    ManagedIdentityCredential: managed identity timed out. See https://aka.ms/azsdk/go/identity/troubleshoot#dac for more information
    AzureCLICredential: Azure CLI not found on path
    AzureDeveloperCLICredential: Azure Developer CLI not found on path"
ACME CA=https://acme-staging-v02.api.letsencrypt.org/directory acmeCA=https://acme-staging-v02.api.letsencrypt.org/directory domains=["*.domain.com","domain.com"] providerName=le-staging.acme routerName=to-sup@file rule=Host(`sup.domain.com`)
```
