### ISSUE TITLE
Netcup - credentials error

### ISSUE THREAD

**Issue by JustNZ** [go-acme/lego#1349]
I'm using Traefik on Rancher and want to use my provider netcup for acme. Somehow it doesn't work.

The container log have the following error: 
`cannot get ACME client netcup: some credentials information are missing: NETCUP_CUSTOMER_NUMBER,NETCUP_API_KEY,NETCUP_API_PASSWORD"`

My secret on rancher:
![image](https://user-images.githubusercontent.com/51332147/108102952-8b031e80-7089-11eb-978c-a4ced8128cf6.png)

ACME App Config:

```
acme: 
    enabled: true
    email: "email@email.com"
    onHostRule: true
    staging: true
    logging: true
    challengeType: "dns-01"
    dnsProvider:
      name: "netcup"
      existingSecretName: "netcupsecret"
```
