### ISSUE TITLE
Add SLSA provenance to your releases

### ISSUE THREAD

**Issue by udf2457** [go-acme/lego#2167]
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

Please add [SLSA provenance ](https://slsa.dev/)to your releases.

It is easy to do on on Github:

https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/generic/README.md#provenance-for-goreleaser
https://goreleaser.com/blog/slsa-generation-for-your-artifacts/#slsa-github-generator

Background info:
https://docs.sigstore.dev/signing/overview/

**Comment by udf2457** [comment]
Just to update this, new option has emerged since 2024 to use GH Attestations https://docs.github.com/en/actions/how-tos/secure-your-work/use-artifact-attestations/use-artifact-attestations instead to achieve the same goal if it helps.

**Comment by ldez** [comment]
FYI, we already have GH attestations.

**Comment by udf2457** [comment]
The annoying thing about GH attestations is (AFAIK) they are largely dependent on the `gh` CLI tool to verify, which in turn requires a GH login which is is a non-starter for automated scripted deployments.

IIRC that problem is not present with SLSA3.

**Comment by udf2457** [comment]
H/T @mara004 in https://github.com/cli/cli/issues/11803#issuecomment-4674400878 who pointed out a work-around.

@ldez If you are willing to add the attestation as a release artifact, then verification can be done without a requirement for GH login, e.g. 

```sh
$ wget https://github.com/pypdfium2-team/pypdfium2/releases/download/5.9.0/pypdfium2-5.9.0.tar.gz
$ wget https://github.com/pypdfium2-team/pypdfium2/releases/download/5.9.0/pypdfium2-attestation.json
$ gh attestation trusted-root > trusted_root.jsonl   # This `gh attestation` flag does not require a GH login
$ gh attestation verify pypdfium2-5.9.0.tar.gz -R pypdfium2-team/pypdfium2 --bundle pypdfium2-attestation.json --custom-trusted-root trusted_root.jsonl
Loaded digest sha256:db1274bd27844db6fda17ef1dbcd0026c47d357437058d838e98060c0da9e92e for file://pypdfium2-5.9.0.tar.gz
Loaded 1 attestations from pypdfium2-attestation.json

The following policy criteria will be enforced:
- Predicate type must match:................ https://slsa.dev/provenance/v1
- Source Repository Owner URI must match:... https://github.com/pypdfium2-team
- Source Repository URI must match:......... https://github.com/pypdfium2-team/pypdfium2
- Subject Alternative Name must match regex: (?i)^https://github.com/pypdfium2-team/pypdfium2/
- OIDC Issuer must match:................... https://token.actions.githubusercontent.com

✓ Verification succeeded!

The following 1 attestation matched the policy criteria

- Attestation #1
  - Build repo:..... pypdfium2-team/pypdfium2
  - Build workflow:. .github/workflows/main.yaml@refs/heads/main
  - Signer repo:.... pypdfium2-team/pypdfium2
  - Signer workflow: .github/workflows/main.yaml@refs/heads/main
```

As mentioned my @mara004 in their reply to me, this attestation file artifact is not to be confused with the `Release attestation (json)` file that GH automagically adds.  The latter is not usable for attestation verification, or at least not without a login.

**Comment by ldez** [comment]
The attestation process creates this https://github.com/go-acme/lego/attestations

**Comment by mara004** [comment]
> The attestation process creates this https://github.com/go-acme/lego/attestations

Yes, but there is no way to programmatically download these without authenticating with a GH token.
By attaching the attestations file as a release artifact (like LLVM, pdfium-binaries, pypdfium2 and others do), the need for a GH token is avoided.

**Comment by udf2457** [comment]
Well, yes, `bundle-path` is an output from `actions/attest` but it is not uploaded to your release.  I don't see the generated attestations in your releases, and that's the critical bit.

Yes they might be available indirectly via the workflow as per the link you provide, but getting them indirectly in a scripted manner requires a GitHub login for API access.  Getting them via your release artifacts does not, as per my example above.

As you can see from `pypdfium2-team/pypdfium2` published by @mara004, they are explicitly renaming it and uploading it:

```yml
      - name: Rename provenance file
        run: mv "$SRC_PATH" pypdfium2-attestation.json
        env:
          SRC_PATH: ${{ steps.provenance.outputs.bundle-path }}
      
      # FIXME skip gh_only/*.whl if !inputs.augment
      - name: Publish to GitHub
        uses: ncipollo/release-action@v1
        with:
          immutableCreate: true
          artifacts: 'dist/*.whl,gh_only/*.whl,dist/*.tar.gz,pypdfium2-attestation.json'
          bodyFile: 'RELEASE.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ needs.build.outputs.new_version }}
          prerelease: ${{ contains(needs.build.outputs.new_version, 'b') }}
```

I am not workflow expert but I think in the context of your workflow you would need to split out the attestations and upload the results, maybe something like this:

```yml
- name: Attest Checksums
        id: attest_checksums
        uses: actions/attest@v4
        with:
          subject-checksums: ./dist/lego_${{ fromJSON(steps.goreleaser.outputs.metadata).version }}_checksums.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest Digests
        id: attest_digests
        uses: actions/attest@v4
        with:
          subject-checksums: ./dist/digests.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Attestations to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Rename bundles to avoid filename collisions on the release
          cp "${{ steps.attest_checksums.outputs.bundle-path }}" ./checksums-attestation.jsonl
          cp "${{ steps.attest_digests.outputs.bundle-path }}" ./digests-attestation.jsonl
          
          # Upload the renamed bundles to the current release tag
          # N.B. `gh` is suggested here because `actions/upload-release-asset` is archived and no longer maintained
          gh release upload ${{ github.ref_name }} \
            ./checksums-attestation.jsonl \
            ./digests-attestation.jsonl \
            --clobber
```

at the end instead of your present:

```yml
      - uses: actions/attest@v4
        with:
          subject-checksums: ./dist/lego_${{ fromJSON(steps.goreleaser.outputs.metadata).version }}_checksums.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/attest@v4
        with:
          subject-checksums: ./dist/digests.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
```
