### ISSUE TITLE
OVH DNS-01: "Error when call OVH api to add record : Error 404: This service does not exist"

### ISSUE THREAD

**Issue by PlqnK** [go-acme/lego#618]
Hi!
I'm using Traefik (v1.6.5) and it's having issues renewing/creating Let's Encrypt certificates for my services just like described here on the Traefik repository: https://github.com/containous/traefik/issues/3415 where someone said that it's an issue with lego.
Here's what shows up in my logs:
```
Error when call OVH api to add record : "Error 404: \"This service does not exist\""                                                                                                
time="2018-08-13T07:56:16Z" level=error msg="Unable to obtain ACME certificate for domains \"subdomain.domain.tld\" detected thanks to rule \"Host:subdomain.domain.tld\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[subdomain.domain.tld] Error presenting token: Error 404: \"This service does not exist\"\n"
```
Here's the relevant part of my `docker-compose.yml`:
```yml
version: "2"
services:
  traefik:
    # https://hub.docker.com/_/traefik/
    image: traefik
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${LOCAL_STORAGE}/traefik/config/traefik.toml:/etc/traefik/traefik.toml
      - ${LOCAL_STORAGE}/traefik/config/acme.json:/acme.json
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_NAME}"
```
The relevant part of my .env file:
```
## Global
LOCAL_STORAGE=/usr/local/share/docker-containers/data
DOMAIN_NAME=domain.tld

## Traefik
# See here to know which variables you need to set for your specific provider https://docs.traefik.io/configuration/acme/#provider
# For OVH first go to https://eu.api.ovh.com/createApp/ and create an API Application then type in a shell: curl -XPOST -H"X-Ovh-Application: YOURAPPKEY" -H "Content-type: application/json" https://eu.api.ovh.com/1.0/auth/credential  -d '{"accessRules":[{"method":"GET","path":"/*"},{"method":"POST","path":"/*"},{"method":"PUT","path":"/*"},{"method":"DELETE","path":"/*"}]}'
OVH_ENDPOINT=ovh-eu
OVH_APPLICATION_KEY=xxxxxxxxxxxxxxxx
OVH_APPLICATION_SECRET=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
OVH_CONSUMER_KEY=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
And my traefik.toml file:
```toml
debug = false
logLevel = "ERROR"

defaultEntryPoints = ["https","http"]
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
      users = ["admin:$mypasswordhash"]

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.tld"
watch = true
exposedbydefault = false

[acme]
email = "me@example.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
  [acme.dnsChallenge]
  # https://docs.traefik.io/configuration/acme/#provider
  provider = "OVH"
  delayBeforeCheck = 0
```
I want to point out that the certificate generation worked when I set up Traefik for the first time ~3 months ago and I deleted the ACME generated TXT records from my DNS zone since then (I don't know if it's relevant or not). I also tried to stop & delete the Traefik container, delete the acme.json file and recreate the Traefik container for it to try to generate the certificates like it was the first run but no luck, same error message in the logs.

Don't hesitate to ask if you want me to test something and thanks for taking the time to read me!
